/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package Interfaces;

import DTOs.ContactoDTO;
import Funcionalidad.MostrarContactoSS;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DTOs.PersonaDTO;

/**
 *
 * @author Oley
 */
public class FrmCrearGrupo extends javax.swing.JPanel implements java.beans.Customizer {

    private PersonaDTO personaDTO;
    private Object bean;

    /**
     * Creates new customizer FrmCrearGrupo
     */
    public FrmCrearGrupo(PersonaDTO personaDTO) {
        this.personaDTO = personaDTO;
        initComponents();
        cargarContactos();

    }

    public void setPersonaDTO(PersonaDTO personaDTO) {
        this.personaDTO = personaDTO;
        cargarContactos();
    }

    public void setObject(Object bean) {
        this.bean = bean;
    }

    private void cargarContactos() {
        if (personaDTO != null && personaDTO.getCurp() != null) {
            // Obtiene la lista de contactos
            MostrarContactoSS mostrarContactoSS = new MostrarContactoSS();
            List<ContactoDTO> listaContactos = mostrarContactoSS.obtenerContactosDTOPersona(personaDTO);

            // Si la lista de contactos no es nula, la muestra en la tabla
            if (listaContactos != null) {
                // Configura el modelo de la tabla
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.addColumn("Nombre");
                modelo.addColumn("Apellido Paterno");
                // Añade las filas con los datos de los contactos
                for (ContactoDTO contacto : listaContactos) {
                    modelo.addRow(new Object[]{contacto.getNombre(), contacto.getApellidoP()});
                }
                // Establece el modelo en la tabla
                jTable1.setModel(modelo);
            } else {
                // Si la lista de contactos es nula, muestra un mensaje de error
                JOptionPane.showMessageDialog(this, "No se pudo obtener la lista de contactos");
            }
        } else {
            // Si personaDTO no es válido, muestra un mensaje de error
            JOptionPane.showMessageDialog(this, "PersonaDTO no es válido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jButton2.setText("Continuar");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 420, 220));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setForeground(new java.awt.Color(153, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crear Grupo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel2)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  // Crear una instancia del menú principal
    MenuPrincipal menuPrincipal = new MenuPrincipal(personaDTO);

    // Hacer visible el menú principal
    menuPrincipal.setVisible(true);

    // Ocultar el formulario actual
    this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
