/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import DAOS.TarjetaDAO;
import DTOs.ContactoDTO;
import DTOs.PersonaDTO;
import DTOs.TarjetaDTO;
import DTOs.TransferenciaDTO;
import Funcionalidad.ITarjetaSS;
import Funcionalidad.ITransferenciaSS;
import Funcionalidad.TarjetaSS;
import Funcionalidad.TransferenciaSS;
import Interfaces.ConfirmacionAñadirTarjeta;
import Interfaces.MenuPrincipal;
import interfaces.daos.ITarjetaDAO;
import java.text.Normalizer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class TransferenciaConfirmacion extends javax.swing.JFrame {

    ITransferenciaSS transferenciaSS;
    ITarjetaSS tarjetaSS;
    TarjetaDTO tarjetaDTO;
    TarjetaDTO tarjetaDestino;
    ContactoDTO contactoDTO;
    TransferenciaDTO transferenciaDTO;

    /**
     * Creates new form MenuPrincipal
     */
    public TransferenciaConfirmacion(TarjetaDTO tarjetaDesti, TarjetaDTO tarjeta, TransferenciaDTO transferencia, ContactoDTO contacto) {

        initComponents();

        transferenciaSS = new TransferenciaSS();
        tarjetaSS = new TarjetaSS();
        tarjetaDestino = tarjetaDesti;
        tarjetaDTO = tarjeta;
        contactoDTO = contacto;
        transferenciaDTO = transferencia;

        txtImporte.setText("" + transferencia.getImporte());
        txtNumTarjeta.setText(contactoDTO.getNumeroCuenta());
        txtTitular.setText(contactoDTO.getNombre());

    }

    public String igualaValores(String cadena1) {
        String cadenaNormalizada1 = Normalizer.normalize(cadena1, Normalizer.Form.NFD)
                .replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
        return cadenaNormalizada1;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumTarjeta = new javax.swing.JTextField();
        txtTitular = new javax.swing.JTextField();
        txtImporte = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Confirmación de Trasnferencia");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setForeground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Confirmación de transferencia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Numero de tarjeta:");

        btnCancelar.setText("Regresar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Titular:");

        jLabel4.setText("Importe");

        txtNumTarjeta.setEditable(false);
        txtNumTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumTarjetaActionPerformed(evt);
            }
        });

        txtTitular.setEditable(false);

        txtImporte.setEditable(false);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumTarjeta)
                            .addComponent(txtTitular, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(txtImporte)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FrmSeleccionarContacto menuPrincipal = new FrmSeleccionarContacto(tarjetaDTO); // Instancia el formulario principal
        menuPrincipal.setVisible(true); // Muestra el formulario principal
        this.dispose(); // Cierra el formulario actual
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNumTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumTarjetaActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        TarjetaDTO tarjetaBuena = tarjetaSS.obtenerTarjetaDTOPorNumero(tarjetaDestino);
        if (tarjetaBuena != null) {
            PersonaDTO personaDTO = tarjetaSS.obtenerPersonaDeTarjeta(tarjetaBuena);
            if (personaDTO != null) {

                String contactoNombre = this.igualaValores(contactoDTO.getNombre());
                String personaNombre = this.igualaValores(personaDTO.getNombre());
                String contactoAP = this.igualaValores(contactoDTO.getApellidoP());
                String personaAP = this.igualaValores(personaDTO.getApellidoP());
//                System.out.println("cN " + contactoNombre);
//                System.out.println("cAP " + contactoAP);
//                System.out.println("pN " + personaNombre);
//                System.out.println("pAP " + personaAP);

                if (personaNombre.equalsIgnoreCase(contactoNombre) && personaAP.equalsIgnoreCase(contactoAP)
                        && tarjetaBuena.getBanco().equals(contactoDTO.getBanco())
                        && tarjetaBuena.getNumeroCuenta().equalsIgnoreCase(contactoDTO.getNumeroCuenta())) {

                    if (transferenciaSS.realizarTransferencia(transferenciaDTO)) {
//                         Transferencia exitosa

                        TransferenciaExitosa t = new TransferenciaExitosa(transferenciaDTO, tarjetaDTO);
                        t.show();
                        dispose();
                    } else {
//                         Saldo insuficiente
                        JOptionPane.showMessageDialog(this, "Saldo insuficiente: \nCuentas con $"+ tarjetaDTO.getSaldo() + " y quieres enviar $" + txtImporte.getText()
                                , "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Datos del Contacto Incorrectos favor de revisarlos", "Error", JOptionPane.ERROR_MESSAGE);
                    FrmSeleccionarContacto sc = new FrmSeleccionarContacto(tarjetaDTO);
                    sc.show();
                    this.dispose();
                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Datos del Contacto Incorrectos favor de revisarlos", "Error", JOptionPane.ERROR_MESSAGE);
            FrmSeleccionarContacto sc = new FrmSeleccionarContacto(tarjetaDTO);
            sc.show();
            this.dispose();
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtNumTarjeta;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables
}
